/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#e5e2e1",
        "border-strong": "#C7C7C0",
        "surface-container-low": "#f5f3ee",
        "tertiary-fixed-dim": "#c9c6c1",
        "tertiary-container": "#575651",
        "on-error-container": "#93000a",
        "secondary": "#5f5e5e",
        "on-primary": "#ffffff",
        "surface-variant": "#e4e2dd",
        "border-subtle": "#DEDED8",
        "surface-container-highest": "#e4e2dd",
        "ink": "#171717",
        "on-secondary": "#ffffff",
        "primary-fixed": "#ffdad8",
        "surface-container-lowest": "#ffffff",
        "surface": "#FFFFFF",
        "inverse-on-surface": "#f2f1eb",
        "on-error": "#ffffff",
        "surface-tint": "#ad2f37",
        "on-secondary-fixed-variant": "#474746",
        "outline-variant": "#e0bfbd",
        "on-primary-container": "#ffb9b7",
        "on-secondary-container": "#636262",
        "secondary-fixed-dim": "#c8c6c5",
        "on-tertiary-fixed": "#1c1c18",
        "on-background": "#1b1c19",
        "on-surface-variant": "#584140",
        "background": "#fbf9f4",
        "on-primary-fixed": "#410007",
        "surface-bright": "#fbf9f4",
        "primary-fixed-dim": "#ffb3b1",
        "surface-dim": "#dbdad5",
        "surface-container-high": "#eae8e3",
        "inverse-primary": "#ffb3b1",
        "primary": "#80091b",
        "error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#474743",
        "on-tertiary": "#ffffff",
        "surface-container": "#efeee9",
        "primary-container": "#a1262f",
        "on-surface": "#1b1c19",
        "burgundy": "#A1262F",
        "secondary-container": "#e2dfde",
        "paper": "#F7F4EE",
        "outline": "#8c706f",
        "tertiary-fixed": "#e5e2dc",
        "error": "#ba1a1a",
        "on-secondary-fixed": "#1c1b1b",
        "tertiary": "#3f3f3b",
        "inverse-surface": "#30312d",
        "on-primary-fixed-variant": "#8c1522",
        "on-tertiary-container": "#cdcbc5"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "base": "4px",
        "unit-1": "4px",
        "unit-2": "8px",
        "unit-3": "12px",
        "unit-4": "16px",
        "unit-6": "24px",
        "unit-8": "32px",
        "unit-12": "48px",
        "unit-16": "64px",
        "gutter": "24px",
        "margin-mobile": "16px",
        "margin-desktop": "80px",
        "reading-max": "720px",
        "container-max": "1280px"
      },
      fontFamily: {
        "display-xl": ["Manrope", "sans-serif"],
        "display-xl-mobile": ["Manrope", "sans-serif"],
        "h1": ["Manrope", "sans-serif"],
        "h2": ["Manrope", "sans-serif"],
        "h3": ["Manrope", "sans-serif"],
        "body-lead": ["Inter", "sans-serif"],
        "body-default": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-semibold": ["Inter", "sans-serif"],
        "caption": ["Inter", "sans-serif"]
      },
      fontSize: {
        "display-xl": ["64px", {"lineHeight": "72px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "display-xl-mobile": ["44px", {"lineHeight": "48px", "fontWeight": "700"}],
        "h1": ["40px", {"lineHeight": "48px", "fontWeight": "700"}],
        "h2": ["32px", {"lineHeight": "40px", "fontWeight": "700"}],
        "h3": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "body-lead": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "body-default": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "label-semibold": ["13px", {"lineHeight": "18px", "fontWeight": "600"}],
        "caption": ["12px", {"lineHeight": "16px", "fontWeight": "500"}]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
