'use client';
import { useEffect, useState } from 'react';
import { Button } from '@/app/components/ui';

type Question={id:string;number:number;stem:string;questionType:'multiple_choice'|'true_false'|'short_answer'|'essay';options?:{key:string;text:string}[]};
type Assessment={assessmentId:string;title:string;questions:Question[]};
async function call<T>(url:string,init?:RequestInit){const r=await fetch(url,init);const j=await r.json() as {data?:T;error?:{code?:string;message?:string}};if(!r.ok){const message=j.error?.code==='SHARE_REVOKED'?'Tautan asesmen telah dicabut.':j.error?.code==='SHARE_EXPIRED'?'Tautan asesmen kedaluwarsa.':j.error?.message??'Terjadi kesalahan.';throw new Error(message)}return j.data as T}
export default function StudentRunner({token}:{token:string}){
 const [phase,setPhase]=useState<'loading'|'identity'|'starting'|'running'|'done'|'error'>('loading');
 const [data,setData]=useState<Assessment>(); const [name,setName]=useState(''); const [klass,setKlass]=useState(''); const [attempt,setAttempt]=useState(''); const [answers,setAnswers]=useState<Record<string,string>>({}); const [error,setError]=useState(''); const [submitting,setSubmitting]=useState(false);
 useEffect(()=>{let active=true;call<Assessment>(`/v1/public/shares/${encodeURIComponent(token)}`).then(x=>{if(active){setData(x);setPhase('identity')}}).catch(e=>{if(active){setError(e.message);setPhase('error')}});return()=>{active=false}},[token]);
 useEffect(()=>{if(phase!=='running'||!attempt||!Object.keys(answers).length)return;const timer=setTimeout(()=>{void call(`/v1/public/shares/${encodeURIComponent(token)}/attempts/${encodeURIComponent(attempt)}/answers`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({answers})}).catch(()=>{})},500);return()=>clearTimeout(timer)},[answers,attempt,phase,token]);
 async function start(){setPhase('starting');try{const x=await call<{id:string}>(`/v1/public/shares/${encodeURIComponent(token)}/attempts`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({guestName:name.trim(),...(klass.trim()?{guestClass:klass.trim()}: {})})});setAttempt(x.id);setPhase('running')}catch(e){setError((e as Error).message);setPhase('error')}}
 async function submit(){setSubmitting(true);setError('');try{await call(`/v1/public/shares/${encodeURIComponent(token)}/attempts/${encodeURIComponent(attempt)}/submit`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({answers})});setPhase('done')}catch(e){setError((e as Error).message)}finally{setSubmitting(false)}}
 if(phase==='loading'||phase==='starting')return <main className="min-h-screen grid place-items-center" aria-busy="true"><p>Memuat asesmen…</p></main>;
 if(phase==='error')return <main className="min-h-screen grid place-items-center px-4"><div role="alert">{error}</div></main>;
 if(phase==='done')return <main className="min-h-screen grid place-items-center px-4"><div role="status" className="text-center"><h1 className="text-xl font-semibold">Jawaban berhasil dikirim</h1><p>Terima kasih, {name}.</p></div></main>;
 if(phase==='identity')return <main className="min-h-screen grid place-items-center px-4"><form className="w-full max-w-md space-y-4" onSubmit={e=>{e.preventDefault();void start()}}><h1 className="text-xl font-semibold">{data?.title}</h1><div><label htmlFor="name">Nama</label><input id="name" required value={name} onChange={e=>setName(e.target.value)} className="w-full border rounded px-3 py-2" /></div><div><label htmlFor="class">Kelas (opsional)</label><input id="class" value={klass} onChange={e=>setKlass(e.target.value)} className="w-full border rounded px-3 py-2" /></div><Button type="submit" disabled={!name.trim()}>Mulai asesmen</Button></form></main>;
 return <main className="mx-auto min-h-screen max-w-2xl space-y-8 px-4 py-8"><h1 className="text-xl font-semibold">{data?.title}</h1>{data?.questions.map(q=>{const choices=q.questionType==='true_false'?(q.options?.length?q.options:[{key:'true',text:'Benar'},{key:'false',text:'Salah'}]):q.options;return <section key={q.id}><p className="font-medium">{q.number}. {q.stem}</p>{q.questionType==='multiple_choice'||q.questionType==='true_false'?<fieldset><legend className="sr-only">Pilihan jawaban soal {q.number}</legend>{choices?.map(o=><label key={o.key} className="block"><input type="radio" name={q.id} checked={answers[q.id]===o.key} onChange={()=>setAnswers(a=>({...a,[q.id]:o.key}))}/> {o.key}. {o.text}</label>)}</fieldset>:<textarea aria-label={`Soal ${q.number}`} rows={q.questionType==='essay'?5:2} value={answers[q.id]??''} onChange={e=>setAnswers(a=>({...a,[q.id]:e.target.value}))} className="w-full border rounded px-3 py-2"/>}</section>})}{error&&<div role="alert">{error}</div>}<Button loading={submitting} onClick={()=>void submit()}>{error?'Coba kirim lagi':'Kirim jawaban'}</Button></main>
}
